apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pods
  template:
    metadata:
      labels:
        app: pods
    spec:
      nodeSelector:                     
        env: prod                           
      containers:
        - name: container1
          image: nginx
          ports:
            - containerPort: 80
