apiVersion: v1
kind: Service
metadata:
  name: my-cluster-ip
spec: 
  type: ClusterIP                
  selector:
    name: nginx                   
  ports:
    - name: http                  
      port: 30002               
      targetPort: 8080
