apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
  namespace: custom-ns
spec:
  clusterIP: None 
  selector:
    app: pods
  ports:
    - name: http
      port: 30001
      targetPort: 8080
