apiVersion: v1
kind: Service
metadata:
  name: my-node-port
spec: 
  type: NodePort               
  selector:
    app: ip-app               
  ports:
    - name: http                 
      port: 30002        
	  targetPort: 8080  
	  nodePort: 30001
