apiVersion: v1
kind: Service
metadata:
  name: node-port-demo
spec: 
  type: NodePort               
  selector:
    app: ip-app               
  ports:
    - name: http                 
      port: 30002        
      targetPort: 8080  
      nodePort: 30001
