apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-demo
  namespace: test
subjects:														
  - kind: ServiceAccount
    name: sa-role-binding-demo										
roleRef: 
  kind: Role
  name: role-demo
