apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-role-binding-demo
  namespace: default
subjects:														
  - kind: ServiceAccount
    name: my-sa										
roleRef: 
  kind: Role
  name: my-role
