apiVersion: rbac.authorization.k8s.io/v1
kind: Role                                              
metadata:
  name: role-demo
  namespace: test                              
rules:       
  - apiGroups: [""]                               
    resources: ["pods"]                           
    verbs: ["get","watch","list","delete","create","apply"]
  - apiGroups: [""]
    resources: ["deployments"]
	verbs: ["get","watch","list","delete","create","apply"]
  - apiGroups: [""]
    resources: ["services"]
	verbs: ["get","watch","list","delete"]
